### ISSUE TITLE
tm_create_tables looking for a nonexisting user

### ISSUE THREAD

**Issue by alecrimi** [TissueMAPS/TmLibrary#31]
I am doing an installation from scratch of the new version of TM
I have tried to run tm_create_tables after the installation of the new tmlibrary (usind git clone and then sudo pip install .).
This is the error: 

> Traceback (most recent call last):
  File "/usr/local/bin/tm_create_tables", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/tissuemaps/src/tmlibrary/src/tmlibrary/bin/tm_create_tables", line 35, in <module>
    create_tables(args.db_uri)
  File "/home/ubuntu/tissuemaps/src/tmlibrary/src/tmlibrary/bin/tm_create_tables", line 22, in create_tables
    tm.MainModel.metadata.create_all(engine)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 3860, in create_all
    tables=tables)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1919, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1912, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2103, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2142, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1456, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2138, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1135, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 179, in connect
    connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "tissuemaps"
FATAL:  password authentication failed for user "tissuemaps"

> 
It is looking for a user named tissuemaps, but in the postgres db there is only the default user created according to the guide.

> postgres=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
>
This postgres user has the same password on;
ALTER USER postgres WITH PASSWORD 'XXX';
echo 'localhost:5432:tissuemaps:postgres:XXX' > ~/.pgpass
and 
[DEFAULT]
db_password = XXX

**Comment by HackerMD** [comment]
> sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL: password authentication failed for user "tissuemaps"
FATAL: password authentication failed for user "tissuemaps"

It says user `tissuemaps`, not `postgres`!

**Comment by alecrimi** [comment]
exactly! According to the guide the default user is postgres, then we have to change the[ guide](https://github.com/TissueMAPS/TissueMAPS/blob/master/docs/installation.rst) : 

> sudo

 -u postgres psql postgres
\password postgres
\q
>
>
CREATE USER postgres;
ALTER USER postgres WITH SUPERUSER;
ALTER USER postgres WITH PASSWORD 'XXX';
>

**Comment by HackerMD** [comment]
How did you install packages? Did you checkout the `master` branch or release tag `v0.1.1`?

Keep in mind that the TissueMAPS repository as well as the docs refer to the current release (see [README](https://github.com/TissueMAPS/TissueMAPS/blob/master/README.rst)) and not to the latest version of code.

**Comment by alecrimi** [comment]
Using the commnad
git clone --recursive https://github.com/TissueMAPS/TissueMAPS.git ~/tissuemaps
which according to the guid, shuold checkout to the latest release (which I assume is v0.1.1). Right?
The I have to check the users and don't assume the guide is updated

**Comment by HackerMD** [comment]
How does your config file look like in `~/.tmaps/tissuemaps.cfg`?

The default user is `postgres` (see [tmlib.config](https://github.com/TissueMAPS/TmLibrary/blob/877791d8a8e80cba49ee0cec3942b527e3ef5da0/tmlib/config.py#L68)), but somehow user `tissuemaps` is used.

`tm_create_tables` directly accessed property [tmlib.config.TmapsConfig. db_uri_sqla](https://github.com/TissueMAPS/TmLibrary/blob/877791d8a8e80cba49ee0cec3942b527e3ef5da0/tmlib/config.py#L68) (see [here](https://github.com/TissueMAPS/TmLibrary/blob/877791d8a8e80cba49ee0cec3942b527e3ef5da0/bin/tm_create_tables#L20)).

**Comment by alecrimi** [comment]
as I said, in the  ~/.pgpass, ~/.tmaps/tissuemaps.cfg and while doing ALTER USER postgres WITH PASSWORD 'XXX';
there is the same password.
The problem persists even when I create a new user called "tissuemaps"

**Comment by HackerMD** [comment]
What is the value of key "db_user" in `~/.tmaps/tissuemaps.cfg`?

```ini
[DEFAULT]
db_user = ???
```

**Comment by alecrimi** [comment]
I tried setting both "postgres" and "tissuemaps" with no success. I suspect something went wrong with the installation of postgres or tmlibs. I do it from scratch this part before continuing banging our heads

**Comment by alecrimi** [comment]
removing and re-installing postgres solved the problem
